name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run:
        sudo apt update
        sudo apt-get install python3
        pip3 install Django
        python3 manage.py test
